# Generated by Django 5.0.6 on 2024-07-18 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0031_alter_technicianevent_appointment_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box_Cut_Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_complete", models.BooleanField(default=False)),
                ("box_cut_drop_used", models.BooleanField(default=False)),
                ("box_cut_hd_box", models.BooleanField(default=False)),
                ("box_cut_cut_length", models.BooleanField(default=False)),
                ("box_prep_track_notch", models.BooleanField(default=False)),
                ("box_prep_drill_holes_top_back", models.BooleanField(default=False)),
                (
                    "box_prep_drill_holes_front_bottom",
                    models.BooleanField(default=False),
                ),
                ("hem_bar_drop_used", models.BooleanField(default=False)),
                ("hem_bar_hd_hem_bar", models.BooleanField(default=False)),
                ("hem_bar_cut_length", models.BooleanField(default=False)),
                ("hem_bar_drill_end_cap_screws", models.BooleanField(default=False)),
                ("hem_bar_drill_hook_hole", models.BooleanField(default=False)),
                ("tracks_drop_used", models.BooleanField(default=False)),
                ("tracks_hd_tracks", models.BooleanField(default=False)),
                ("tracks_cut_length", models.BooleanField(default=False)),
                ("tracks_drill_mounting_holes", models.BooleanField(default=False)),
                ("tracks_drill_hook_hole", models.BooleanField(default=False)),
                ("tube_drop_used", models.BooleanField(default=False)),
                ("tube_length", models.BooleanField(default=False)),
                ("tube_cut_length", models.BooleanField(default=False)),
                ("l_channel_drop_used", models.BooleanField(default=False)),
                ("l_channel_quantity", models.BooleanField(default=False)),
                ("l_channel_cut_length", models.BooleanField(default=False)),
                ("l_channel_drill_hook_hole", models.BooleanField(default=False)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_cut_jobs",
                        to="main.unit",
                    ),
                ),
            ],
        ),
    ]
