# Generated by Django 5.0.6 on 2024-07-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_technicianevent_appointment_notes_and_more"),
        ("workstation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tube_Cut_Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_complete", models.BooleanField(default=False)),
                ("tube_drop_used", models.BooleanField(default=False)),
                ("tube_length", models.BooleanField(default=False)),
                ("tube_cut_length", models.BooleanField(default=False)),
                ("stock_drop_used", models.BooleanField(default=False)),
                ("stock_cut_length", models.BooleanField(default=False)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tube_cut_jobs",
                        to="main.unit",
                    ),
                ),
            ],
        ),
    ]
