# Generated by Django 5.0.6 on 2024-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeline",
            name="type",
            field=models.CharField(
                choices=[
                    ("ti", "Technical Issues"),
                    ("of", "Order Finalized"),
                    ("rma", "RMA"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=64,
            ),
        ),
    ]
