# Generated by Django 5.0.6 on 2024-06-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_order_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unit",
            old_name="drop_manual",
            new_name="drop",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="drop_motorized",
            new_name="width",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="box_color_manual",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="box_color_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="cable_mount_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="cable_size_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="fabric_color_manual",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="fabric_color_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="fabric_type_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="handing_manual",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="handing_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="hardware_color_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="mounting_manual",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="mounting_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="product_type_manual",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="product_type_motorized",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="unit_count",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="width_manual",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="width_motorized",
        ),
        migrations.AddField(
            model_name="unit",
            name="accessory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sun & Wind Sensor", "Sun & Wind Sensor"),
                    ("Wind Sensor", "Wind Sensor"),
                    ("16FT Motor Wire", "16FT Motor Wire"),
                    ("32FT Motor Wire", "32FT Motor Wire"),
                    ("(T) Touch-Up Paint - Black", "(T) Touch-Up Paint - Black"),
                    ("(T) Touch-Up Paint - Bronze", "(T) Touch-Up Paint - Bronze"),
                    (
                        "(T) Touch-Up Paint - Dk. Beige",
                        "(T) Touch-Up Paint - Dk. Beige",
                    ),
                    ("(T) Touch-Up Paint - Ivory", "(T) Touch-Up Paint - Ivory"),
                    ("(T) Touch-Up Paint - Grey", "(T) Touch-Up Paint - Grey"),
                    (
                        "(T) Touch-Up Paint - Lt. Beige",
                        "(T) Touch-Up Paint - Lt. Beige",
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="box_color",
            field=models.CharField(
                blank=True, choices=[("Bronze", "Bronze")], max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="cable_mount",
            field=models.CharField(
                blank=True,
                choices=[("Floor Mount", "Floor Mount")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="cable_size",
            field=models.CharField(
                blank=True, choices=[("12FT", "12FT")], max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="fabric_color",
            field=models.CharField(
                blank=True,
                choices=[("Dark Bronze", "Dark Bronze")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="fabric_type",
            field=models.CharField(
                blank=True,
                choices=[("Suntex 95", "Suntex 95")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="hand_brace",
            field=models.CharField(
                blank=True,
                choices=[('48" Brown', '48" Brown')],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="handing",
            field=models.CharField(
                blank=True,
                choices=[("Left", "Left"), ("Right", "Right")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="hardware_color",
            field=models.CharField(
                blank=True, choices=[("Brown", "Brown")], max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="mounting",
            field=models.CharField(
                blank=True,
                choices=[("Side, 2 L-Channel", "Side, 2 L-Channel")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="pile_brush",
            field=models.CharField(
                blank=True,
                choices=[("Standard", "Standard")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HD Elite FRT", "HD Elite FRT"),
                    ("STD Box Shade", "STD Box Shade"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="motor_type",
            field=models.CharField(
                blank=True,
                choices=[("Premium Sense 25", "Premium Sense 25")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="remote_type",
            field=models.CharField(
                blank=True,
                choices=[("Smartline 5 Channel", "Smartline 5 Channel")],
                max_length=100,
                null=True,
            ),
        ),
    ]
