# Generated by Django 5.0.6 on 2024-06-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_drop_manual_unit_drop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="installation_address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="ship_via",
            field=models.CharField(
                choices=[("OLD DOMINION", "OLD DOMINION")], max_length=100
            ),
        ),
    ]
