# Generated by Django 5.0.6 on 2024-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_order_installation_address_alter_order_ship_via"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="installation_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
