# Generated by Django 5.0.6 on 2024-06-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_order_installation_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="po_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
