# Generated by Django 5.0.6 on 2024-06-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_order_po_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="unit_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main.customer",
            ),
        ),
    ]
