# Generated by Django 5.0.6 on 2024-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_unit_unit_number_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
