# Generated by Django 5.0.6 on 2024-07-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_crew_technicianevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="crew_type",
            field=models.CharField(
                choices=[
                    ("Technician", "technician"),
                    ("Sales", "sales"),
                    ("Delivery", "delivery"),
                ],
                default=1,
                max_length=60,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="crew",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
