# Generated by Django 5.0.6 on 2024-07-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_crew_crew_type_alter_crew_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianevent",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technicianevent",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician_events",
                to="main.order",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="technicianevent",
            name="visit_type",
            field=models.CharField(
                choices=[
                    ("Installation", "installation"),
                    ("Warranty Service", "warranty"),
                    ("Tech Measure", "techmeasure"),
                    ("Service", "service"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="technicianevent",
            name="crew",
            field=models.CharField(
                choices=[("Crew 1", "c1"), ("Crew 2", "c2"), ("Crew 3", "c3")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="technicianevent",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.crew"
            ),
        ),
        migrations.CreateModel(
            name="SalesEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "active"),
                            ("Estimate", "estimate"),
                            ("Sold", "sold"),
                            ("Cancelled", "cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_events",
                        to="main.order",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.crew"
                    ),
                ),
            ],
        ),
    ]
