# Generated by Django 5.0.6 on 2024-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_salesevent_address_salesevent_appointment_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="crew_type",
            field=models.CharField(
                choices=[
                    ("technician", "Technician"),
                    ("sales", "Sales"),
                    ("delivery", "Delivery"),
                ],
                max_length=60,
            ),
        ),
    ]
