# Generated by Django 5.0.6 on 2024-07-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_remove_technicianevent_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technicianevent",
            old_name="title",
            new_name="address",
        ),
        migrations.AddField(
            model_name="technicianevent",
            name="appointment_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicianevent",
            name="main_phone",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
