# Generated by Django 5.0.6 on 2024-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_technicianevent_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianevent",
            name="appointment_status",
            field=models.BooleanField(
                choices=[(1, "Active"), (0, "Inactive")], default=0
            ),
        ),
    ]
