# Generated by Django 5.0.6 on 2024-07-07 01:27

import django.db.models.deletion
import main.models
import main.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_document_galleryimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasabigallery",
            name="image",
            field=models.ImageField(
                storage=main.storages.WasabiStorage(), upload_to="gallery/"
            ),
        ),
        migrations.CreateModel(
            name="CustomerFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=main.storages.WasabiStorage(),
                        upload_to=main.models.customer_directory_path,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wasabi_files",
                        to="main.order",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WasabiFile",
        ),
    ]
