# Generated by Django 5.0.6 on 2024-07-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_wasabigallery_image_customerfile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianevent",
            name="visit_type",
            field=models.CharField(
                choices=[
                    ("installation", "Installation"),
                    ("warranty", "Warranty Service"),
                    ("tech", "Tech Measure"),
                    ("service", "Service"),
                ],
                max_length=100,
            ),
        ),
    ]
