# Generated by Django 5.0.6 on 2024-07-08 09:02

import django.utils.timezone
import main.models
import main.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_rename_wasabigallery_customergalleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergalleryimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customergalleryimage",
            name="image",
            field=models.ImageField(
                storage=main.storages.WasabiStorage(),
                upload_to=main.models.customer_gallery_path,
            ),
        ),
    ]
