# Generated by Django 5.0.6 on 2024-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_customergalleryimage_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("estimate", "Estimate"),
                    ("sold", "Sold"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=100,
            ),
        ),
    ]
