# Generated by Django 5.0.6 on 2024-07-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_alter_salesevent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryevent",
            name="main_phone",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryevent",
            name="route",
            field=models.CharField(
                choices=[("azloop", "AZ Loop"), ("route1", "Route 1")],
                default="azloop",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("delivered", "Delivered"),
                            ("notdelivered", "Not Delivered"),
                            ("missing", "Missing Part"),
                        ],
                        default=False,
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_jobs",
                        to="main.order",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="jobs",
            field=models.ManyToManyField(related_name="delivery_events", to="main.job"),
        ),
        migrations.DeleteModel(
            name="GroupedJob",
        ),
    ]
