# Generated by Django 5.0.6 on 2024-07-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_deliveryevent_main_phone_deliveryevent_route_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryevent",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
