# Generated by Django 5.0.6 on 2024-07-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_deliveryevent_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianevent",
            name="crew",
            field=models.CharField(
                blank=True,
                choices=[("c1", "Crew 1"), ("c2", "Crew 2"), ("c3", "Crew 3")],
                max_length=20,
                null=True,
            ),
        ),
    ]
