# Generated by Django 5.0.6 on 2024-07-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_technicianevent_crew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("notdelivered", "Not Delivered"),
                    ("missing", "Missing Part"),
                ],
                default="notdelivered",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="salesevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("estimate", "Estimate"),
                    ("sold", "Sold"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=100,
            ),
        ),
    ]
